version: '3.9'

services:
  solace:
    image: solace/solace-pubsub-standard
    ports:
      - "8080:8080"
      - "55555:55555"
      - "8008:8008"
      - "1883:1883"
      - "8000:8000"
      - "5672:5672"
      - "9000:9000"
      - "2222:2222"
    shm_size: 2g
    environment:
      username_admin_globalaccesslevel: admin
      username_admin_password: admin

  db:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: compose-postgres
    ports:
      - "5050:80"
    depends_on:
      - db
  sub:
    image: 'user-service-sub:latest'
    restart: on-failure
    build:
      context: ./subscriber
    depends_on:
      - db
      - solace
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/compose-postgres
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: compose-postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  pub:
    image: 'user-service-pub:latest'
    restart: on-failure
    build:
      context: ./publisher
    depends_on:
      - solace
      - sub
